url: https://notyoursurvivor.github.io
baseurl: /

# Site settings
title: Not Your Survivor
email: notyoursurvivor@gmail.com
description: "Not Your Survivor offers a candid exploration of the effects of family sexual abuse, and a road map for how to support loved ones who've been affected by family sexual abuse."


# Team names, titles and social links
people:
- name: Alex Robertson
  pic: 1
  position: Founder, Creative Director
  social:
    - title: linkedin
      url:  https://www.linkedin.com/in/arrobertson/
    - title: github
      url:  https://github.com/codesrobertson


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/not-your-survivor
  - title: youtube
    url: https://www.youtube.com/channel/UCtHrJew8Qo7ePr3H6YR8aGw
  - title: instagram
    url: https://www.instagram.com/not_your_survivor/
  - title: soundcloud
    url: https://soundcloud.com/user-900539222
  - title: spotify
    url: https://open.spotify.com/user/nu0ywdqiq561p49sas97rqmmw?si=bb03026d405c47e3



# Postal address (add as many lines as necessary)
address:
  - line: Seattle, WA

# Build settings
markdown: kramdown
permalink: pretty
